sudo: required
os:
  - osx
lenguage: node_js
node_js:
  - 4.0
env:
- TRAVIS_NODE_VERSION="6"
script:
  - echo "Deploying!"
install:
  - brew update
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install
  - npm run install_hugo
  - npm install -g firebase-tools
  script:
  - echo "Generating WEB with HUGO"
  - npm run lint
  - cd exampleSite
  - hugo server --destination=../public --appendPort=false --baseU=https://ebron.tech
  - cd ..
after_success:
  - firebase deploy --token $FIRE_TOKEN
